(in-package :drawer)

(ql:quickload :vicentino-tunings)


(let* ((btikz (make-backend-tikz :filename "vicentino-bars-thirds.tex"))
       (int-terza-maggiore 5/4)
       (int-terza-minore 6/5)
       (int-terza-minore-mt (/ 6/5 (expt 81/80 1/4)))
       (int-i 11/9)
       (int-iia 60/49)
       (int-iib 49/40)
       (int-iii (* (sqrt 25/24) 6/5))
       (int-list (sort (copy-list (list (cons int-terza-maggiore "5:4")
                                        (cons int-terza-minore "6:5")
                                        (cons int-terza-minore-mt "IV ($\\frac{6}{5}\\frac{1}{\\sqrt[4]{\\frac{81}{80}}}$)")
                                        (cons int-i "I (11:9)")
                                        (cons int-iia "IIa (60:49)")
                                        (cons int-iib "IIb (49:40)")
                                        (cons int-iii "III ($\\frac{6}{5}\\sqrt{\\frac{25}{24}}$)")))
                       #'<
                       :key #'car))
       (bar-padding 3.5)
       (scale-factor 1/10)
       (label-padding 1)
       (bar-thickness 2.5)
       (bars-gr (gr (loop for len in int-list
                        for i from 0
                           collect
                           (let ((log-len (* scale-factor
                                             (vicentino-tunings:ratio->length (car len)))))
                             (gr (list (ln-shape (pt 0 (- (* i bar-padding)
                                                          (* 1/2 bar-thickness)))
                                           (list log-len bar-thickness (- log-len)))
                                       (make-text (format nil "~a" (cdr len))
                                                  (pt (+ log-len label-padding)
                                                      (* i bar-padding))
                                                  :h-align :left))))))))
  (draw-with-multiple-backends (list btikz) (list bars-gr))
  (compile-tikz btikz))

(let* ((btikz (make-backend-tikz :filename "vicentino-bars-thirds-major.tex"))
       (int-terza-maggiore 5/4)
       (int-quarta 4/3)
       (int-quarta-mt (* 4/3 (expt 81/80 1/4)))
       (int-i 9/7)
       (int-iia 40/31)
       (int-iib 31/24)
       (int-iii (* 5/4 (sqrt 16/15)))
       (int-list (sort (copy-list (list (cons int-terza-maggiore "5:4")
                                        (cons int-quarta "4:3")
                                        (cons int-quarta-mt "IV ($\\frac{4}{3}\\sqrt{\\frac{81}{80}}$)")
                                        (cons int-i "I (9:7)")
                                        (cons int-iia "IIa (40:31)")
                                        (cons int-iib "IIb (31:24)")
                                        (cons int-iii "III ($\\frac{5}{4}\\sqrt{\\frac{16}{15}}$)")))
                       #'<
                       :key #'car))
       (bar-padding 3.5)
       (scale-factor 1/10)
       (label-padding 1)
       (bar-thickness 2.5)
       (bars-gr (gr (loop for len in int-list
                          for i from 0
                          collect
                          (let ((log-len (* scale-factor
                                            (vicentino-tunings:ratio->length (car len)))))
                            (gr (list (ln-shape (pt 0 (- (* i bar-padding)
                                                         (* 1/2 bar-thickness)))
                                                (list log-len bar-thickness (- log-len)))
                                      (make-text (format nil "~a" (cdr len))
                                                 (pt (+ log-len label-padding)
                                                     (* i bar-padding))
                                                 :h-align :left))))))))
  (draw-with-multiple-backends (list btikz) (list bars-gr))
  (compile-tikz btikz))


(let* ((btikz (make-backend-tikz :filename "vicentino-bars-thirds-propinqui.tex"))
       (int-terza-minore-mt (vicentino-tunings:interval :tuning1 :c :up :e♭))
       (int-terza-minore-propinqua (vicentino-tunings:interval :tuning1 :c :up :Ė♭))
       (int-terza-minore-iii (* (sqrt 25/24) 6/5))
       (int-terza-maggiore (vicentino-tunings:interval :tuning1 :c :up :e))
       (int-terza-maggiore-propinqua (vicentino-tunings:interval :tuning1 :c :up :Ė))
       (int-terza-maggiore-iii (* 5/4 (sqrt 16/15)))
       (int-quarta-minima (vicentino-tunings:interval :tuning1 :c :up :e♯))
       (int-quarta-mt (vicentino-tunings:interval :tuning1 :c :up :f))
       (int-list (sort (copy-list (list (cons int-terza-minore-mt "terza minore [archicembalo]")
                                        (cons int-terza-minore-propinqua "terza più di minore [archicembalo]")
                                        (cons int-terza-minore-iii "terza più di minore [III]")
                                        (cons int-terza-maggiore "terza maggiore [archicembalo]")
                                        (cons int-terza-maggiore-propinqua "terza più di maggiore [archicembalo]")
                                        (cons int-terza-maggiore-iii "terza più di maggiore [III]")
                                        (cons int-quarta-minima "[quarta minima, archicembalo]")
                                        (cons int-quarta-mt "quarta [archicembalo]")))
                       #'<
                       :key #'car))
       (bar-padding 3.5)
       (scale-factor 1/10)
       (label-padding 1)
       (bar-thickness 2.5)
       (bars-gr (gr (loop for len in int-list
                          for i from 0
                          collect
                          (let ((log-len (* scale-factor
                                            (vicentino-tunings:ratio->length (car len)))))
                            (gr (list (ln-shape (pt 0 (- (* i bar-padding)
                                                         (* 1/2 bar-thickness)))
                                                (list log-len bar-thickness (- log-len)))
                                      (make-text (format nil "~a" (cdr len))
                                                 (pt (+ log-len label-padding)
                                                     (* i bar-padding))
                                                 :h-align :left))))))))
  (draw-with-multiple-backends (list btikz) (list bars-gr))
  (compile-tikz btikz))




(let* ((btikz (make-backend-tikz :filename "ji-intervals"))
       (int-ottava 2/1)
       (int-quinta 3/2)
       (int-quarta 4/3)
       (int-terza-maggiore 5/4)
       (int-terza-minore 6/5)
       (int-sesquiottavo 9/8)
       (int-sesquinono 10/9)
       (int-semitono-maggiore 16/15)
       (int-semitono-minore 25/24)
       (int-diesis 128/125)
       (int-comma 81/80)
       (int-list (sort (copy-list (list
                                   (cons int-ottava "2:1, ottava")
                                   (cons int-quinta "3:2, quinta")
                                   (cons int-quarta "4:3, quarta")
                                   (cons int-terza-maggiore "5:4, terza maggiore")
                                   (cons int-terza-minore "6:5, terza minore")
                                   (cons int-sesquiottavo "9:8, tono sesquiottavo")
                                   (cons int-sesquinono "10:9, tono sesquinono")
                                   (cons int-semitono-maggiore "16:15, semitono maggiore")
                                   (cons int-semitono-minore "25:24, semitono minore")
                                   (cons int-diesis "128:125, diesis enarmonico")
                                   (cons int-comma "81:80, comma (syntonisches Komma)")))
                       #'<
                       :key #'car))
       (bar-padding 3.5)
       (scale-factor 1/10)
       (label-padding 1)
       (bar-thickness 2.5)
       (bars-gr (gr (loop for len in int-list
                        for i from 0
                           collect
                           (let ((log-len (* scale-factor
                                             (vicentino-tunings:ratio->length (car len)))))
                             (gr (list (ln-shape (pt 0 (- (* i bar-padding)
                                                          (* 1/2 bar-thickness)))
                                           (list log-len bar-thickness (- log-len)))
                                       (make-text (format nil "~a" (cdr len))
                                                  (pt (+ log-len label-padding)
                                                      (* i bar-padding))
                                                  :h-align :left))))))))
  (draw-with-multiple-backends (list btikz) (list bars-gr))
  (compile-tikz btikz))

(let* ((btikz (make-backend-tikz :filename "historical-intervals"))
       (int-ottava 2/1)
       (int-quinta 3/2)
       (int-quarta 4/3)
       (int-terza-maggiore 5/4)
       (int-terza-minore 6/5)
       (int-sesquiottavo 9/8)
       (int-sesquinono 10/9)
       (int-semitono-maggiore 16/15)
       (int-semitono-minore 25/24)
       (int-diesis 128/125)
       (int-comma 81/80)
       (int-terza-minore-mt (vicentino-tunings:interval :tuning1 :d :up :f))
       (int-quinta-mt (vicentino-tunings:interval :tuning1 :d :up :a))
       (int-quarta-mt (vicentino-tunings:interval :tuning1 :d :up :g))
       (int-tono-mt (vicentino-tunings:interval :tuning1 :d :up :e))
       (int-semitono-maggiore-mt (vicentino-tunings:interval :tuning1 :e :up :f))
       (int-semitono-minore-mt (vicentino-tunings:interval :tuning1 :d :up :d♯))
       (int-fifth-eq (vicentino-tunings:interval :12ed2 :c :up :g))
       (int-fourth-eq (vicentino-tunings:interval :12ed2 :c :up :f))
       (int-major-third-eq (vicentino-tunings:interval :12ed2 :c :up :e))
       (int-minor-third-eq (vicentino-tunings:interval :12ed2 :c :up :e♭))
       (int-major-second-eq (vicentino-tunings:interval :12ed2 :c :up :d))
       (int-minor-second-eq (vicentino-tunings:interval :12ed2 :c :up :d♭))
       (int-augmented-unison-eq (vicentino-tunings:interval :12ed2 :c :up :c♯))
       (int-ditonus 81/64)
       (int-semiditonus (* 3/2 64/81))
       (int-limma 256/243)
       (int-apotome 2187/2048)
       (int-comma-pyth 531441/524288)
       (int-list (sort (copy-list (list
                                   (cons int-comma-pyth "531441:524288, comma (pythagoreische Stimmung)")
                                   (cons int-ottava "2:1, diapason (pythagoreische Stimmung)")
                                   (cons int-quinta "3:2, diapente (pythagoreische Stimmung)")
                                   (cons int-quarta "4:3, diatessaron (pythagoreische Stimmung)")
                                   (cons int-ditonus "81:64, ditonus (pythagoreische Stimmung)")
                                   (cons int-semiditonus "32:27, semiditonus (pythagoreische Stimmung)")
                                   (cons int-sesquiottavo "9:8, tonus (pythagoreische Stimmung)")
                                   (cons int-limma "256:243, limma (diatonischer Halbton in pythagoreischer Stimmung)")
                                   (cons int-apotome "2187:2048, apotome (chromatischer Halbton in pythagoreischer Stimmung)")
                                   (cons int-fifth-eq "fifth in Equal Temperament")
                                   (cons int-fourth-eq "fourth in Equal Temperament")
                                   (cons int-major-third-eq "major-third in Equal Temperament")
                                   (cons int-minor-third-eq "minor-third in Equal Temperament")
                                   (cons int-major-second-eq "major-second in Equal Temperament")
                                   (cons int-minor-second-eq "minor-second in Equal Temperament")
                                   (cons int-augmented-unison-eq "augmented-unison in Equal Temperament")

                                   (cons int-quinta-mt "mitteltönige Quinte")
                                   (cons int-quarta-mt "mitteltönige Quarte")
                                   (cons int-terza-maggiore "mitteltönige grosse Terz")
                                   (cons int-terza-minore-mt "mitteltönige kleine Terz")
                                   (cons int-tono-mt "mitteltöniger Ganzton")
                                   (cons int-semitono-maggiore-mt "mitteltöniger diatonischer Halbton")
                                   (cons int-semitono-minore-mt "mitteltöniger chromatischer Halbton")
                                   (cons int-diesis "mitteltöniger enharmonischer Schritt")


                                   (cons int-ottava "2:1, ottava")
                                   (cons int-quinta "3:2, quinta")
                                   (cons int-quarta "4:3, quarta")
                                   (cons int-terza-maggiore "5:4, terza maggiore")
                                   (cons int-terza-minore "6:5, terza minore")
                                   (cons int-sesquiottavo "9:8, tono sesquiottavo")
                                   (cons int-sesquinono "10:9, tono sesquinono")
                                   (cons int-semitono-maggiore "16:15, semitono maggiore")
                                   (cons int-semitono-minore "25:24, semitono minore")
                                   (cons int-diesis "128:125, diesis enarmonico")
                                   (cons int-comma "81:80, comma (syntonisches Komma)")))
                       #'<
                       :key #'car))
       (bar-padding 3.5)
       (scale-factor 1/10)
       (label-padding 1)
       (bar-thickness 2.5)
       (bars-gr (gr (loop for len in int-list
                        for i from 0
                           collect
                           (let ((log-len (* scale-factor
                                             (vicentino-tunings:ratio->length (car len)))))
                             (gr (list (ln-shape (pt 0 (- (* i bar-padding)
                                                          (* 1/2 bar-thickness)))
                                           (list log-len bar-thickness (- log-len)))
                                       (make-text (format nil "~a" (cdr len))
                                                  (pt (+ log-len label-padding)
                                                      (* i bar-padding))
                                                  :h-align :left))))))))
  (draw-with-multiple-backends (list btikz) (list bars-gr))
  (compile-tikz btikz))
