(in-package :drawer)

(let* ((btikz (make-backend-tikz :filename "vicentino-arbore.tex"))
       (max-height 50)
       (y-base 5)
       (origin (pt 0 0))
       (vert-line (ln origin (pt 0 max-height)))
       (comma 0.5)
       (diesis-minore 1)
       (diesis-maggiore 2)
       (semitono-minore 2)
       (semitono-maggiore 3)
       (tono 5)
       (terza-minore 8)
       (terza-maggiore 10)
       (quarta 13)
       (quinta 18)
       (interval-dot (circ 0 0 0.2 :style-update '(:fill :fill)))
       (home-row
         (gr (mapcar (lambda (int)
                       (cp interval-dot origin (pt int y-base)))
                     (list semitono-maggiore tono terza-minore terza-maggiore quarta quinta)))))
  (draw-with-multiple-backends (list btikz) (list (ln origin (pt 10 10))))
  ;; (compile-tikz btikz)
  )
