(in-package :drawer)



(let ((system (make-tonnetz '(8 8 2) '(0 0 0))))
  (flet ((insert-node (label subscripts ratio)
           (set-node system
                     subscripts
                     (format nil "\\fbox{~a}\\\\\\tiny ~a ~a"
                             (* (expt 3 (second subscripts))
                                (expt 5 (first subscripts))
                                (expt 7 (third subscripts)))
                             label
                             ratio))))
    (insert-node "XII" '(0 0 0) 1024)
    (insert-node "XII" '(0 2 1) 1008)
    (insert-node  "XII" '(3 0 0) 1000)
    (insert-node  "XI" '(0 5 0) 972)
    (insert-node  "XI" '(1 1 0) 960)
    (insert-node  "XI" '(1 3 1) 945)
    (insert-node  "X" '(2 2 0) 900)
    (insert-node  "X" '(0 0 1) 896)
    (insert-node  "IX" '(0 3 0) 864)
    (insert-node  "IX" '(1 1 1) 840)
    (insert-node  "VIII" '(1 4 0) 810)
    (insert-node  "VIII" '(2 0 0) 800)
    (insert-node  "VII" '(0 1 0) 768)
    (insert-node  "VII" '(0 3 1) 756)
    (insert-node  "VII" '(3 1 0) 750)
    (insert-node  "VI" '(0 6 0) 729)
    (insert-node  "VI" '(1 2 0) 720)
    (insert-node  "VI" '(2 0 1) 700)
    (insert-node  "V" '(2 3 0) 675)
    (insert-node  "V" '(0 1 1) 672)
    (insert-node  "IV" '(0 4 0) 648)
    (insert-node  "IV" '(1 0 0) 640)
    (insert-node  "IV" '(1 2 1) 630)
    (insert-node  "III" '(2 1 0) 600)
    (insert-node  "II" '(0 2 0) 576)
    (insert-node  "II" '(0 4 1) 567)
    (insert-node  "II" '(1 0 1) 560)
    (insert-node  "I" '(1 3 0) 540)
    (insert-node  "I" '(2 1 1) 525))
  (add-connections system '(1 0 0) :style-update '(:line-thickness :normal))
  (add-connections system '(0 1 0) :style-update '(:line-thickness :thick))
  (add-connections system '(0 0 1) :style-update '(:line-type :dashed))
  (let* ((btikz (make-backend-tikz :filename "tonnetz-meyer.tex"))
         (ts (render system (pt 30 30) (list (pt 18 0)
                                             (pt 0 18)
                                             (rotate-point (pt 0 -8.5) 145))
                     2.5)))
    (draw-with-multiple-backends (list btikz) (list ts))
    (compile-tikz btikz)))
